project_id = "geimemclslezirwtuvkh"

[functions.generate-reminders]
verify_jwt = false

[functions.upload-to-drive]
verify_jwt = true

[functions.google-drive-auth]
verify_jwt = true

[functions.google-drive-callback]
verify_jwt = false

[functions.google-drive-status]
verify_jwt = true
